// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travel_Website_System_API.Models;

[Table("Admin")]
public partial class Admin
{
    [Key]
    public int adminId { get; set; }

    public int? userId { get; set; }

    [InverseProperty("admin")]
    public virtual ICollection<Package> Packages { get; set; } = new List<Package>();

    [ForeignKey("userId")]
    [InverseProperty("Admins")]
    public virtual User user { get; set; }
}