// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travel_Website_System_API.Models
{
    public class Chat
    {
       
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedDate { get; set; }
        public string Description { get; set; }
        public string Logo { get; set; }
        public bool IsDeleted { get; set; }


        public virtual ICollection<Message> Messages { get; set; } = new HashSet<Message>();

        [ForeignKey("customerService")]
        public string? customerServiceId { get; set; }
        public virtual CustomerService customerService { get; set; }
       
        [ForeignKey("client")]
        public string? clientId { get; set; }
        public virtual Client client { get; set; }

    }
}