// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travel_Website_System_API.Models;

[Table("Chat")]
public partial class Chat
{
    [Key]
    public int chatId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column(TypeName = "text")]
    public string Description { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Logo { get; set; }

    public int? customerServiceId { get; set; }

    public int? clientId { get; set; }

    [InverseProperty("chat")]
    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    [ForeignKey("clientId")]
    [InverseProperty("Chats")]
    public virtual Client client { get; set; }

    [ForeignKey("customerServiceId")]
    [InverseProperty("Chats")]
    public virtual CustomerService customerService { get; set; }
}