// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travel_Website_System_API.Models;

[Table("Client")]
public partial class Client
{
    [Key]
    public int clientId { get; set; }

    public int userId { get; set; }

    [InverseProperty("client")]
    public virtual ICollection<BookingPackage> BookingPackages { get; set; } = new List<BookingPackage>();

    [InverseProperty("client")]
    public virtual ICollection<BookingService> BookingServices { get; set; } = new List<BookingService>();

    [InverseProperty("client")]
    public virtual ICollection<Chat> Chats { get; set; } = new List<Chat>();

    [InverseProperty("client")]
    public virtual ICollection<LovePackage> LovePackages { get; set; } = new List<LovePackage>();

    [InverseProperty("client")]
    public virtual ICollection<LoveService> LoveServices { get; set; } = new List<LoveService>();

    [ForeignKey("userId")]
    [InverseProperty("Clients")]
    public virtual User user { get; set; }
}