// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travel_Website_System_API.Models;

[Table("CustomerService")]
public partial class CustomerService
{
    [Key]
    public int customerServiceId { get; set; }

    public int? userId { get; set; }

    [InverseProperty("customerService")]
    public virtual ICollection<Chat> Chats { get; set; } = new List<Chat>();

    [ForeignKey("userId")]
    [InverseProperty("CustomerServices")]
    public virtual User user { get; set; }
}