// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travel_Website_System_API.Models
{
    public partial class LoveService
    {
        public int Id { get; set; }
        public DateTime? date { get; set; }
        public bool IsDeleted { get; set; }


        [ForeignKey("client")]
        public string clientId { get; set; }
        public virtual Client client { get; set; }

        [ForeignKey("serviceId")]
        public int serviceId { get; set; }
        public virtual Service service { get; set; }
    }
}