// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travel_Website_System_API.Models;

[PrimaryKey("clientId", "serviceId")]
[Table("LoveService")]
public partial class LoveService
{
    [Key]
    public int clientId { get; set; }

    [Key]
    public int serviceId { get; set; }

    [Column(TypeName = "date")]
    public DateTime? date { get; set; }

    [ForeignKey("clientId")]
    [InverseProperty("LoveServices")]
    public virtual Client client { get; set; }

    [ForeignKey("serviceId")]
    [InverseProperty("LoveServices")]
    public virtual Service service { get; set; }
}