// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travel_Website_System_API.Models
{
    public class Message
    {
        public int Id { get; set; }

        //for chat
        public string SSN { get; set; }

        public string status { get; set; }
        public string sender { get; set; }
        public bool isDeleted { get; set; }

        [ForeignKey("Chat")]
        public int? chatId { get; set; }
        public virtual Chat Chat { get; set; }

        //for chat
        [ForeignKey(nameof(SSN))]
        public ApplicationUser User { get; set; } // Navigation property to ApplicationUser
    }
}