// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travel_Website_System_API.Models
{
    public class Package
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string? Description { get; set; }
        public string? Image { get; set; }
        public int? QuantityAvailable { get; set; } = 4;
        public decimal? Price { get; set; }
        public bool isDeleted { get; set; }
        public DateTime? startDate { get; set; }
        public int? Duration { get; set; }

        public virtual ICollection<BookingPackage> BookingPackages { get; set; } = new HashSet<BookingPackage>();
        public virtual ICollection<LovePackage> LovePackages { get; set; } = new HashSet<LovePackage>();

        [ForeignKey("admin")]
        public string? adminId { get; set; }
        public virtual Admin admin { get; set; }

        [ForeignKey("packageId")]
        [InverseProperty("packages")]
        public virtual ICollection<Service> services { get; set; } = new List<Service>();
    }
}