// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travel_Website_System_API.Models
{
    public class Payment
    {
        public int Id { get; set; }
        public decimal? Amount { get; set; }
        public DateTime? PaymentDate { get; set; }

        public string ?Method { get; set; }
        public bool ?IsDeleted { get; set; } = false;
        //The status of the payment (e.g., "Created", "Completed", "Failed").
        public string ?PaymentStatus { get; set; }
        public string? PayPalOrderId { get; set; }

        [ForeignKey("BookingPackage")]
        public int? BookingPackageId { get; set; }
        public virtual BookingPackage BookingPackage { get; set; }

        [ForeignKey("BookingService")]
        public int? BookingServiceId { get; set; }
        public virtual BookingService BookingService { get; set; }
    }
}