// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;

namespace Travel_Website_System_API.Models;

[Table("Payment")]
public partial class Payment
{
    [Key]
    public int PaymentID { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Amount { get; set; }

    [Column(TypeName = "date")]
    public DateTime Date { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]

    [AllowNull]
    public string  Method { get; set; }
    [AllowNull]
    public string Currencey { get; set; } = "USD";

    public int? BookingPackageId { get; set; }

    public int? BookingServiceId { get; set; }

    [ForeignKey("BookingPackageId")]
    [InverseProperty("Payments")]
    public virtual BookingPackage BookingPackage { get; set; }

    [ForeignKey("BookingServiceId")]
    [InverseProperty("Payments")]
    public virtual BookingService BookingService { get; set; }
}