// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travel_Website_System_API.Models;

public partial class ServiceProvider
{
    [Key]
    public int serviceProviderId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column(TypeName = "text")]
    public string Description { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Logo { get; set; }

    public bool? isDeleted { get; set; }

    [InverseProperty("serviceProvider")]
    public virtual ICollection<Service> Services { get; set; } = new List<Service>();
}