// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Numerics;
using Microsoft.EntityFrameworkCore;
using Travel_Website_System_API_.Models;

namespace Travel_Website_System_API.Models
{

    public class Service
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ?Description { get; set; }
        public string ?Image { get; set; }
        public int? QuantityAvailable { get; set; } = 4;
        public DateTime? StartDate { get; set; }// choose statrt in service 
        public decimal? price { get; set; }
        public bool? isDeleted { get; set; } = false;
        public int ? BookingTimeAllowed { get; set;}
        public int ? Duration { get; set; }// choose duration(number of days or nights = duration-1)
        public DateTime? EndDate { get; set; }// calculated
     
        //// for flight
        public string ?GoingFlightSource { get; set; }
        public string ?GoingFlightDestination { get; set; }
        public string ?ComingBackFlightSource { get; set; }
        public string ?ComingBackFlightDesination { get; set; }
       

        // hotels: choose start date , duration
        public PackageLocationEnum? HoltelLocation { get; set;} // makkah , madinah
        public int ?NumberOFAvailableRooms { get; set;}
        public int? NumberOFPersons { get; set; } = 2;// in each room 2 by default if increased add 1 room


    public virtual ICollection<BookingService> BookingServices { get; set; } = new HashSet<BookingService>();

        public virtual ICollection<LoveService> LoveServices { get; set; } = new HashSet<LoveService>();

        [ForeignKey("category")]
        public int? categoryId { get; set; }
        public virtual Category category { get; set; }

        [ForeignKey("serviceProvider")]
        public int? serviceProviderId { get; set; }
        public virtual ServiceProvider serviceProvider { get; set; }
              
       // public virtual ICollection<Package> Packages { get; set; } = new HashSet<Package>();

        public virtual ICollection<PackageService> PackageServices { get; set; } = new HashSet<PackageService>();

    }
}