// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travel_Website_System_API.Models;

[Index("SSN", Name = "UQ__Users__CA1E8E3C7CEBD894", IsUnique = true)]
public partial class User
{
    [Key]
    public int userId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string UserName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Fname { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Lname { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Gender { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string SSN { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Password { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Role { get; set; }

    [InverseProperty("user")]
    public virtual ICollection<Admin> Admins { get; set; } = new List<Admin>();

    [InverseProperty("user")]
    public virtual ICollection<Client> Clients { get; set; } = new List<Client>();

    [InverseProperty("user")]
    public virtual ICollection<CustomerService> CustomerServices { get; set; } = new List<CustomerService>();
}