// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace Travel_Website_System_API.Models
{
   
    public class ApplicationUser : IdentityUser
    {

        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Gender { get; set; }
        public string SSN { get; set; }
        public string Role { get; set; }
        public Admin? Admin { get; set; }
        public Client? client { get; set; }
        public bool IsDeleted { get; set; }


        public string? VerificationCode { get; set; }
        public bool IsVerified { get; set; }


        public CustomerService? customerService { get; set; }
        public string PassportNumber { get; set; }
        public string ResidanceCountry { get; set; }
        //for chat signalR
        public ICollection<Message> Messages { get; set; }
        public override string UserName
        {
            get => Email;
            set => base.UserName = Email;
        }

        //for chat signalR

        public string ProfilePictureUrl { get;  set; }

        public string Status { get;  set; }
        public DateTime LastSeen { get;  set; }
        public ApplicationUser User { get;  set; }
        
    }
}

